# Generated by Django 3.0.4 on 2020-04-07 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='country',
        ),
    ]
